In [13]:
import random
import pickle as cPickle
import numpy as np
import math
import pandas
import tensorflow as tf
from sklearn.cluster import *
from sklearn import preprocessing

tf.reset_default_graph()
random.seed(2016)
sampleNum = 10

def completeTrajectories():
    path = './X.npy'
    x = np.load(path)
    print("===========")
    print(x.shape[0])
    print("===========")
    #top5 = x[:2]
    #print(top5)
    #seq = x[1]
    #print(seq)
    #print(seq.shape[0])
    #simTrjss = cPickle.load(open('./simulated_data/sim_trajectories','rb'))
    simTrjComps = []
    simTrjss = []
    simSeq = []
    numJoints=20
    #dim=3
    allX = []
    allY = []
    allZ = []
    joints = []
    N = 3
    
    for seq in x[:40]:
        print(seq)
        print("===========")
        for i in range(0, seq.shape[0]):
            #print(i)
            #print(seq[i])
            joints = []
            joints = [seq[i][n:n+N] for n in range(0, len(seq[i]), N)]
            print(joints)
            #joints.append(subList)
            simTrjss.append(joints)
        simSeq.append(simTrjss)
     
    
    print("BATATA===============")    
    simSeq_np = np.array(simSeq)
    print(simSeq_np)
    print("BATATA===============") 
    for sseq in simSeq_np:
        for simTrjs in sseq:
            trjsCom = []
            time = 0
            for i in range(0,len(simTrjs)):
                rec = []

                if i==0:
                    # time, locationC, speedC, rotC
                    rec = [time,0,0]#,0]
                else:
                    time = time + 5
                    locC = math.sqrt((simTrjs[i][0]-simTrjs[i-1][0])**2+(simTrjs[i][1]-simTrjs[i-1][1])**2+(simTrjs[i][2]-simTrjs[i-1][2])**2)
                    rec.append(time)
                    rec.append(locC)
                    #rec.append(locC/(simTrjs[i][0]-simTrjs[i-1][0]))
                    rec.append(locC/5)
                    #rec.append(math.atan((simTrjs[i][2]-simTrjs[i-1][2])/ (simTrjs[i][1]-simTrjs[i-1][1])))
                trjsCom.append(rec)
            simTrjComps.append(trjsCom)
    print("DONE=========")
    print(len(simTrjComps))
    cPickle.dump(simTrjComps,open('./simulated_data/sim_traj_humanMvt_complete','wb'))
    return simTrjComps

def computeFeas():
    simTrjCompss = cPickle.load(open('./simulated_data/sim_traj_humanMvt_complete','rb'))
    simTrjFeas = []
    for simTrjComps in simTrjCompss:
        trjsComfea = []
        for i in range(0,len(simTrjComps)):
            rec = []
            if i==0:
                # time, locationC, speedC, rotC
                rec = [0,0,0]#,0]
            else:
                locC = simTrjComps[i][1]
                locCrate = locC/(simTrjComps[i][0]-simTrjComps[i-1][0])
                rec.append(simTrjComps[i][0])
                rec.append(locCrate)
                if locCrate<3:
                    rec.append(0)
                    #rec.append(0)
                else:
                    rec.append(simTrjComps[i][2]-simTrjComps[i-1][2])
                    #rec.append(simTrjComps[i][3]-simTrjComps[i-1][3])
            trjsComfea.append(rec)
        simTrjFeas.append(trjsComfea)
    cPickle.dump(simTrjFeas, open('./simulated_data/sim_traj_humanMvt_feas', 'wb'))
    #print(simTrjFeas)
    return simTrjFeas

def rolling_window(sample, windowsize = 600, offset = 300):
    #print("ROLLING WINDOW")
    timeLength = sample[len(sample)-1][0]
    windowLength = int (timeLength/offset)+1
    windows = []
    for i in range(0,windowLength):
        windows.append([])

    for record in sample:
        time = record[0]
        for i in range(0,windowLength):
            if (time>(i*offset)) & (time<(i*offset+windowsize)):
                windows[i].append(record)
                
   # print(windows)
    return windows
    # pass

def behavior_ext(windows):
    #print("BEHAVIOR EXTTTTTTTTTTT")
    
    behavior_sequence = []
    for window in windows:
        behaviorFeature = []
        records = np.array(window)
        if len(records) != 0:
            # print np.shape(records)
            pd = pandas.DataFrame(records)
            pdd =  pd.describe()
            #print(pdd)
            # print pdd[1][0]
            # for ii in range(1,4):
            #     for jj in range(1,8):
            #         behaviorFeature.append(pdd[ii][jj])
            # behaviorFeature.append(pdd[0][1])
            behaviorFeature.append(pdd[1][1])
            behaviorFeature.append(pdd[2][1])
            #behaviorFeature.append(pdd[3][1])
            # behaviorFeature.append(pdd[0][2])
            # behaviorFeature.append(pdd[1][2])
            # behaviorFeature.append(pdd[2][2])
            # behaviorFeature.append(pdd[3][2])
            # behaviorFeature.append(pdd[0][3])
            behaviorFeature.append(pdd[1][3])
            behaviorFeature.append(pdd[2][3])
            #behaviorFeature.append(pdd[3][3])
            # behaviorFeature.append(pdd[0][4])
            behaviorFeature.append(pdd[1][4])
            behaviorFeature.append(pdd[2][4])
            #behaviorFeature.append(pdd[3][4])
            # behaviorFeature.append(pdd[0][5])
            behaviorFeature.append(pdd[1][5])
            behaviorFeature.append(pdd[2][5])
            #behaviorFeature.append(pdd[3][5])
            # behaviorFeature.append(pdd[0][6])
            behaviorFeature.append(pdd[1][6])
            behaviorFeature.append(pdd[2][6])
            #behaviorFeature.append(pdd[3][6])
            # behaviorFeature.append(pdd[0][7])
            behaviorFeature.append(pdd[1][7])
            behaviorFeature.append(pdd[2][7])
            #behaviorFeature.append(pdd[3][7])

            behavior_sequence.append(behaviorFeature)
    #print(behavior_sequence)
    return behavior_sequence

def generate_behavior_sequences():
    f = open('./simulated_data/sim_traj_humanMvt_feas','rb')
    sim_data = cPickle.load(f)
    behavior_sequences = []

    for sample in sim_data:
        #print(sample)
        windows = rolling_window(sample)
        behavior_sequence = behavior_ext(windows)
        print(len(behavior_sequence))
        behavior_sequences.append(behavior_sequence)
    fout = open('./simulated_data/sim_behavior_humanMvt_sequences','wb')
    cPickle.dump(behavior_sequences,fout)

def generate_normal_behavior_sequence():
    print("generate_normal_behavior_sequence")
    f = open('./simulated_data/sim_behavior_humanMvt_sequences','rb')
    behavior_sequences = cPickle.load(f)
    print(behavior_sequences)
    print(np.shape(behavior_sequences))
    behavior_sequences_normal = []
    templist = []
    for item in behavior_sequences:
        for ii in item:
            templist.append(ii)
        #print (len(item))
    #print(len(templist))
    min_max_scaler = preprocessing.MinMaxScaler()
    # print np.shape(behavior_sequence)
    templist_normal = min_max_scaler.fit_transform(templist).tolist()
    index = 0
    for item in behavior_sequences:
        behavior_sequence_normal = []
        for ii in item:
            behavior_sequence_normal.append(templist_normal[index])
            index = index + 1
        #print(len(behavior_sequence_normal))
        behavior_sequences_normal.append(behavior_sequence_normal)
    #print(index)
    print("generate_normal_behavior_sequence222222222222222")
    print(behavior_sequences_normal)
    fout = open('./simulated_data/sim_normal_behavior_humanMvt_sequences', 'wb')
    cPickle.dump(behavior_sequences_normal, fout)


    
def trajectory2Vec():
    def loopf(prev, i):
        return prev

    # Parameters
    learning_rate = 0.0001
    training_epochs = 300
    display_step = 100

    # Network Parameters
    # the size of the hidden state for the lstm (notice the lstm uses 2x of this amount so actually lstm will have state of size 2)
    size = 100
    # 2 different sequences total
    batch_size = 1
    # the maximum steps for both sequences is 5
    max_n_steps = 17
    # each element/frame of the sequence has dimension of 3
    frame_dim = 12 #18

    input_length = tf.placeholder(tf.int32)

    initializer = tf.random_uniform_initializer(-1, 1)

    # the sequences, has n steps of maximum size
    # seq_input = tf.placeholder(tf.float32, [batch_size, max_n_steps, frame_dim])
    seq_input = tf.placeholder(tf.float32, [max_n_steps, batch_size, frame_dim])
    # what timesteps we want to stop at, notice it's different for each batch hence dimension of [batch]

    # inputs for rnn needs to be a list, each item/frame being a timestep.
    # we need to split our input into each timestep, and reshape it because split keeps dims by default

    useful_input = seq_input[0:input_length[0]]
    loss_inputs = [tf.reshape(useful_input, [-1])]
    encoder_inputs = [item for item in tf.unstack(seq_input)]
    # if encoder input is "X, Y, Z", then decoder input is "0, X, Y, Z". Therefore, the decoder size
    # and target size equal encoder size plus 1. For simplicity, here I droped the last one.
    decoder_inputs = ([tf.zeros_like(encoder_inputs[0], name="GO")] + encoder_inputs[:-1])
    targets = encoder_inputs

    # basic LSTM seq2seq model
    cell = tf.nn.rnn_cell.LSTMCell(size, state_is_tuple=True, use_peepholes=True)
    _, enc_state = tf.contrib.rnn.static_rnn(cell, encoder_inputs, sequence_length=input_length[0], dtype=tf.float32)
    cell = tf.contrib.rnn.OutputProjectionWrapper(cell, frame_dim)
    dec_outputs, dec_state = tf.contrib.legacy_seq2seq.rnn_decoder(decoder_inputs, enc_state, cell, loop_function=loopf)


    # flatten the prediction and target to compute squared error loss
    y_true = [tf.reshape(encoder_input, [-1]) for encoder_input in encoder_inputs]
    y_pred = [tf.reshape(dec_output, [-1]) for dec_output in dec_outputs]

    # Define loss and optimizer, minimize the squared error
    loss = 0
    for i in range(len(loss_inputs)):
        loss += tf.reduce_sum(tf.square(tf.subtract(y_pred[i], y_true[len(loss_inputs) - i - 1])))
    optimizer = tf.train.RMSPropOptimizer(learning_rate).minimize(loss)

    # Initializing the variables
    init = tf.initialize_all_variables()

    # Launch the graph
    with tf.Session() as sess:
        sess.run(init)
        # Training cycle
        input_datas = cPickle.load(open('./simulated_data/sim_normal_behavior_humanMvt_sequences','rb'))
        print("INPUT DATAS")
        print(input_datas)
        trajectoryVecs = []
        j = 0
        for input_data in input_datas:
            print ('Sample:')
            print (j)
            input_len = len(input_data)
            print (input_len)
            defalt = []
            for i in range(0, frame_dim):
                defalt.append(0)
            while len(input_data) < max_n_steps:
                input_data.append(defalt)
            x = np.array(input_data)
            print("shape======")
            print (np.shape(x[0]))
            print(x)
            x = x.reshape((max_n_steps, batch_size, frame_dim))
            embedding = None
            for epoch in range(training_epochs):
                feed = {seq_input: x, input_length: np.array([input_len])}
                # Fit training using batch data
                _, cost_value, embedding, en_int, de_outs, loss_in = sess.run(
                    [optimizer, loss, enc_state, encoder_inputs, dec_outputs, loss_inputs], feed_dict=feed)
                # Display logs per epoch step
                if epoch % display_step == 0:
                    print ("logits")
                    a = sess.run(y_pred, feed_dict=feed)
                    print ("labels")
                    b = sess.run(y_true, feed_dict=feed)

                    print("Epoch:", '%04d' % (epoch + 1), "cost=", "{:.9f}".format(cost_value))
            trajectoryVecs.append(embedding)
            print("Optimization Finished!")
            j = j + 1
        fout = open('./simulated_data/sim_traj_vec_normal_humanMvt_reverse', 'wb')
        cPickle.dump(trajectoryVecs, fout)

def vecClusterAnalysis():
    print ('---------------------------------')
    print ('Our Method')
    trVecs = []
    trs = cPickle.load(open('./simulated_data/sim_traj_vec_normal_humanMvt_reverse','rb'))
    inte = []
    for tr in trs:
        print("-----------")
        print(tr)
        trVecs.append(tr[0][0])
        
    print("TRRR")
    print(tr)
    km = KMeans(n_clusters=3, random_state=2016)
    clusters = km.fit(trVecs).labels_.tolist()
    print("clusters")
    print(clusters)
    all = 0.
    print("###")
    print(clusters[:sampleNum])
    item = set(clusters[:sampleNum])
    print("itemmmm")
    print(item)
    l = []
    for i in item:
        l.append([i,clusters[:sampleNum].count(i)])
        print('Straight dans for:  '+ str(l))
        
    print ('Straight:  '+ str(l))
    m = max([te[1] for te in l])
    print("MAXXX",m)
    all = all + m
    print (float(m)/sampleNum)


    m = 0.
    item = set(clusters[sampleNum:sampleNum*2])
    l = []
    for i in item:
        l.append([i,clusters[sampleNum:sampleNum*2].count(i)])
    print ('Circling:  '+ str(l))
    m = max([te[1] for te in l])
    all = all + m
    print (float(m)/sampleNum)

    m = 0.
    item = set(clusters[sampleNum*2:sampleNum*3])
    l = []
    for i in item:
        l.append([i,clusters[sampleNum*2:sampleNum*3].count(i)])
    m = max([te[1] for te in l])
    print ('bending:   '+ str(l))
    all = all + m
    print (float(m)/sampleNum)
    print ('overall')
    print (all/(sampleNum*3))
    print ('---------------------------------')


if __name__ == '__main__':
    completeTrajectories()
    computeFeas()
    generate_behavior_sequences()
    generate_normal_behavior_sequence()
    trajectory2Vec()
    print("finishhhhhhhhhh")
    #vecClusterAnalysis()

567
[[-0.35713251  0.36986165  2.68409998 ... -0.17262143  0.65932591
   2.54934823]
 [-0.37448502  0.36632716  2.67215094 ... -0.19072368  0.6569371
   2.54794216]
 [-0.37379072  0.36653253  2.67709913 ... -0.1846042   0.65669163
   2.54576767]
 ...
 [-0.28949237  0.36285201  2.76733008 ... -0.15130397  0.67986271
   2.59508208]
 [-0.29884544  0.36511623  2.75388486 ... -0.14562677  0.66912062
   2.58056398]
 [-0.27681412  0.38070862  2.75843502 ... -0.12432163  0.66845585
   2.57404473]]
[array([-0.35713251,  0.36986165,  2.68409998]), array([-1.66066020e-03,  3.54087896e-01,  2.67285988e+00]), array([-0.18035343,  0.40757698,  2.5846011 ]), array([-0.18325419,  0.20669618,  2.77500737]), array([-0.3237759 , -0.01468199,  2.65024112]), array([-0.04489828, -0.02417835,  2.62955171]), array([-0.17490352, -0.00324405,  2.76304837]), array([-0.41915032,  0.11045902,  2.67649601]), array([0.04940912, 0.0926925 , 2.67124733]), array([-0.40116335, -0.17275062,  2.62993544]), array([ 0.03736

[array([-0.3807274 ,  0.35929805,  2.81278179]), array([-0.09000138,  0.41140399,  2.61050881]), array([-0.29538208,  0.42451433,  2.6345648 ]), array([-0.15572836,  0.23797068,  2.78715285]), array([-0.32637603,  0.01737321,  2.73566265]), array([-0.09269509, -0.00286006,  2.58007386]), array([-1.40553173e-01,  1.80798946e-03,  2.76221111e+00]), array([-0.44773791,  0.11144637,  2.79029925]), array([-0.10142565,  0.43985728,  2.35685703]), array([-0.46148851, -0.16600642,  2.76663995]), array([-0.11596216,  0.59616944,  2.13017764]), array([-0.4557379 , -0.23714629,  2.77643063]), array([-0.1177038,  0.6460993,  2.0839765]), array([-0.34897012, -0.55796836,  2.7306958 ]), array([-0.10827569, -0.56614996,  2.6903245 ]), array([-0.35898399, -0.98188526,  2.78099104]), array([-0.08078695, -0.988999  ,  2.74296348]), array([-0.45800047, -0.99560423,  2.64526827]), array([-0.17514955, -1.01211543,  2.60517575]), array([-0.19272021,  0.68316095,  2.60179165])]
[array([-0.38496315,  0.361608

[array([-0.25991471,  0.07203549,  2.9668566 ]), array([-0.02346489,  0.24889342,  2.69720679]), array([-0.24868482,  0.22555542,  2.78366491]), array([0.00365975, 0.02393957, 2.86147031]), array([-0.24527695, -0.20319904,  2.87185341]), array([-0.07457001, -0.17206494,  2.64490385]), array([ 4.80863505e-04, -2.35825649e-01,  2.87897383e+00]), array([-0.23709084,  0.11729174,  2.70910834]), array([-0.03472883,  0.40558481,  2.47675942]), array([-0.20162228,  0.39399933,  2.68112831]), array([-0.07945296,  0.59948212,  2.24645641]), array([-0.19518159,  0.46340687,  2.6538471 ]), array([-0.1036623 ,  0.6597392 ,  2.19791771]), array([-0.0475872 , -0.68569687,  2.73013312]), array([-0.3212555 , -0.64258322,  2.78539491]), array([-0.0803475 , -1.07922877,  2.86633638]), array([-0.26216556, -1.05168225,  2.83371291]), array([-0.09491768, -1.13690471,  2.69303702]), array([-0.43830239, -1.0694631 ,  2.88422629]), array([-0.45051826,  0.15866611,  2.67461619])]
[array([-0.25526748,  0.058959

[array([-0.370262,  0.336608,  2.774969]), array([0.034175, 0.357359, 2.649367]), array([-0.204442,  0.425092,  2.607869]), array([-0.139208,  0.219765,  2.784001]), array([-0.32351 ,  0.062772,  2.69331 ]), array([0.003052, 0.065179, 2.582061]), array([-0.118407,  0.039532,  2.75992 ]), array([-0.417578,  0.05146 ,  2.722689]), array([0.191857, 0.216207, 2.445665]), array([-0.434933, -0.259142,  2.64721 ]), array([0.410952, 0.183373, 2.214601]), array([-0.388908, -0.324535,  2.667282]), array([0.45707 , 0.20545 , 2.149924]), array([-0.336429, -0.515443,  2.625867]), array([-0.054435, -0.505405,  2.721807]), array([ 0.085587, -0.691418,  2.652318]), array([-0.400496, -0.804167,  2.749125]), array([ 2.145000e-03, -8.927790e-01,  2.643976e+00]), array([-0.257761, -0.969026,  2.754313]), array([-0.201028,  0.666485,  2.621388])]
[array([-0.364042,  0.337258,  2.773316]), array([0.034934, 0.364383, 2.632396]), array([-0.207293,  0.42097 ,  2.595355]), array([-0.128617,  0.229403,  2.781229

[array([-0.434711,  0.229303,  2.505758]), array([-0.076113,  0.236848,  2.474925]), array([-0.264316,  0.279807,  2.39822 ]), array([-0.245031,  0.10214 ,  2.579041]), array([-0.447812, -0.119783,  2.471285]), array([-0.021914, -0.11196 ,  2.467158]), array([-0.233881, -0.105853,  2.589597]), array([-0.494695, -0.036811,  2.509576]), array([ 0.012465, -0.020931,  2.486483]), array([-0.464943, -0.310423,  2.421855]), array([ 0.027892, -0.30481 ,  2.435314]), array([-0.485198, -0.375137,  2.410794]), array([ 0.041317, -0.369892,  2.452763]), array([-0.352335, -0.617684,  2.53015 ]), array([-0.114394, -0.6169  ,  2.50647 ]), array([-0.355215, -1.002746,  2.622536]), array([-0.136032, -0.988306,  2.642137]), array([-0.359043, -1.041729,  2.459938]), array([-0.127918, -1.04604 ,  2.485378]), array([-0.261212,  0.524992,  2.377543])]
[array([-0.433939,  0.227745,  2.51    ]), array([-0.075623,  0.238928,  2.47707 ]), array([-0.264683,  0.280903,  2.401945]), array([-0.242646,  0.101621,  2.

[array([-0.34514 ,  0.301511,  2.709982]), array([-0.01479 ,  0.318129,  2.663624]), array([-0.194994,  0.375898,  2.603395]), array([-0.16554 ,  0.165336,  2.737807]), array([-0.343187, -0.021827,  2.64102 ]), array([-0.018452, -0.022879,  2.594749]), array([-0.16493 , -0.025262,  2.729465]), array([-0.384384,  0.030758,  2.700627]), array([0.198629, 0.309461, 2.492418]), array([-0.394715, -0.246039,  2.623241]), array([0.291028, 0.487854, 2.286626]), array([-0.386137, -0.308543,  2.621205]), array([0.334974, 0.509489, 2.246811]), array([-0.2923  , -0.5439  ,  2.685902]), array([-0.057307, -0.541732,  2.674432]), array([-0.296756, -0.957171,  2.771174]), array([ 0.022447, -0.945812,  2.766318]), array([-0.320117, -0.987203,  2.6244  ]), array([ 1.759000e-03, -9.829890e-01,  2.620784e+00]), array([-0.126616,  0.5414  ,  2.610029])]
[array([-0.352687,  0.296827,  2.701441]), array([-0.020214,  0.315301,  2.675429]), array([-0.196699,  0.372864,  2.604877]), array([-0.174452,  0.161167, 

[array([-0.39116415,  0.29913327,  2.70781679]), array([-0.07375771,  0.34229859,  2.60388457]), array([-0.28164197,  0.37476386,  2.51526828]), array([-0.18801602,  0.19079974,  2.72512023]), array([-0.36227299, -0.02616655,  2.63280448]), array([-0.03762428, -0.03810291,  2.52387346]), array([-0.16352877, -0.03470479,  2.68716877]), array([-0.45581043,  0.05298647,  2.69502918]), array([0.07310369, 0.47925858, 2.43947774]), array([-0.41062422, -0.20415013,  2.63113265]), array([0.17970449, 0.66587176, 2.27557569]), array([-0.39741686, -0.26519397,  2.61166761]), array([0.21353794, 0.71911986, 2.27389946]), array([-0.29707676, -0.53254541,  2.69150083]), array([-0.09797241, -0.53567906,  2.6529838 ]), array([-0.29271653, -0.93519481,  2.75095533]), array([-0.07277178, -0.93343655,  2.73563609]), array([-0.34441572, -0.9575257 ,  2.60367677]), array([-0.12304215, -0.96688157,  2.5899819 ]), array([-0.24466565,  0.59549071,  2.57743267])]
[array([-0.3721241 ,  0.30362513,  2.7332355 ]),

[array([-0.37575744,  0.37707819,  2.73065442]), array([0.05345314, 0.39857015, 2.60955478]), array([-0.18659178,  0.45893282,  2.57169231]), array([-0.12336108,  0.24759476,  2.75598871]), array([-0.35500564,  0.02579155,  2.679058  ]), array([0.04230548, 0.0175785 , 2.56844432]), array([-0.11673336,  0.01985683,  2.76619745]), array([-0.40614048,  0.09584685,  2.70709484]), array([0.17883819, 0.57057905, 2.42141241]), array([-0.40933917, -0.20619318,  2.62444371]), array([0.15350041, 0.84369967, 2.27506508]), array([-0.36194802, -0.27364772,  2.60385872]), array([0.20886063, 0.91018504, 2.26197951]), array([-0.26048571, -0.60011874,  2.67399143]), array([-0.01488232, -0.59332814,  2.68958807]), array([-0.27404889, -1.09049194,  2.75346626]), array([-0.01370472, -1.08741518,  2.74344613]), array([-0.33525416, -1.12353933,  2.53929907]), array([-0.07283197, -1.11108025,  2.52743552]), array([-0.13735814,  0.71761558,  2.65883508])]
[array([-0.36601954,  0.40386689,  2.74638281]), array

[array([-0.32264524,  0.32896375,  2.76679047]), array([-0.03423692,  0.33567158,  2.75075615]), array([-0.1854622 ,  0.36750033,  2.64707715]), array([-0.17033022,  0.19396805,  2.85048936]), array([-0.34206352, -0.02737262,  2.73805893]), array([-0.00757568, -0.03727278,  2.71043972]), array([-0.16556716, -0.0237066 ,  2.83318868]), array([-0.39266382,  0.0609604 ,  2.77643895]), array([0.03431557, 0.06720384, 2.7646194 ]), array([-0.40764846, -0.22383615,  2.73914901]), array([ 0.0463073 , -0.22165129,  2.73948977]), array([-0.41659034, -0.27498952,  2.74511755]), array([ 0.05029684, -0.27214515,  2.72465676]), array([-0.29044677, -0.51809627,  2.80806961]), array([-0.07167398, -0.52629344,  2.7735393 ]), array([-0.33033594, -0.90308627,  2.84741178]), array([-0.0635311 , -0.91040047,  2.83433294]), array([-0.33905221, -0.9133586 ,  2.7383248 ]), array([-0.07177146, -0.9276693 ,  2.72608737]), array([-0.17437043,  0.59317852,  2.67880678])]
[array([-0.32851226,  0.32859146,  2.75685

[array([-0.36750558,  0.32998009,  2.76670207]), array([-0.00404513,  0.32746776,  2.77685008]), array([-0.18148746,  0.36970357,  2.65622181]), array([-0.18890457,  0.19876699,  2.87861539]), array([-0.3813531 , -0.02146773,  2.73860964]), array([ 0.03126344, -0.04167447,  2.76838124]), array([-0.18567872, -0.03977109,  2.89546852]), array([-0.43933296,  0.05194266,  2.76622339]), array([0.26767195, 0.33622579, 2.69305326]), array([-0.43000362, -0.23811227,  2.69106553]), array([0.4933235 , 0.50018805, 2.57824382]), array([-0.41436232, -0.30573193,  2.70654768]), array([0.55654723, 0.52380183, 2.56476479]), array([-0.29399426, -0.5580786 ,  2.79705394]), array([-0.05638744, -0.56831492,  2.77739338]), array([-0.29247552, -0.97598068,  2.9023604 ]), array([-0.07398992, -0.98520389,  2.88531061]), array([-0.28526666, -1.0154232 ,  2.74572748]), array([-0.05530207, -1.02620584,  2.73002454]), array([-0.19955801,  0.62035085,  2.72990611])]
[array([-0.37070329,  0.32884591,  2.7758306 ]),

[array([-0.36641076,  0.37686999,  2.75629308]), array([-0.02517466,  0.36899068,  2.64794944]), array([-0.22309088,  0.42059255,  2.61267243]), array([-0.17077702,  0.21544559,  2.79247156]), array([-0.33251595,  0.01162003,  2.70727204]), array([-0.06615631, -0.01988764,  2.62236098]), array([-1.60766658e-01,  1.40756023e-03,  2.78374423e+00]), array([-0.4248939 ,  0.12289198,  2.74553006]), array([0.02471846, 0.20058876, 2.45673146]), array([-0.43772464, -0.15613393,  2.70898188]), array([0.10017122, 0.0648271 , 2.22048691]), array([-0.42903968, -0.22064831,  2.72768474]), array([0.11166155, 0.03699968, 2.15791927]), array([-0.33398867, -0.56916635,  2.73014012]), array([-0.07845939, -0.57959062,  2.69458922]), array([-0.35679539, -0.99217159,  2.78362738]), array([-0.06471645, -1.00470617,  2.73239333]), array([-0.41190378, -1.00921021,  2.62534188]), array([-0.1151301 , -1.02055958,  2.57243416]), array([-0.19387307,  0.67230172,  2.58183559])]
[array([-0.37036577,  0.37238364,  2

[array([-0.23891633,  0.08697513,  2.9523926 ]), array([-0.04246589,  0.2200387 ,  2.64542903]), array([-0.24535984,  0.22484372,  2.76315484]), array([-0.00876477,  0.00564894,  2.81885154]), array([-0.23362187, -0.18541526,  2.88412546]), array([-0.09758634, -0.18195785,  2.63280948]), array([ 0.01289933, -0.20921191,  2.85467542]), array([-0.41067536, -0.04987184,  2.79523338]), array([0.06649107, 0.21570312, 2.40199408]), array([-0.3740285 , -0.30934218,  2.66255479]), array([0.2309213 , 0.27548091, 2.16193618]), array([-0.37341224, -0.38037579,  2.68879282]), array([0.30585336, 0.26202537, 2.12532664]), array([-0.05959907, -0.68173508,  2.73162327]), array([-0.32845268, -0.64554058,  2.81048927]), array([-0.10165455, -1.0801339 ,  2.84718541]), array([-0.27999314, -1.05853814,  2.84184334]), array([-0.11275939, -1.12909893,  2.67399227]), array([-0.45319131, -1.07554545,  2.88533773]), array([-0.20062779,  0.48179179,  2.68070398])]
[array([-0.25779025,  0.14481748,  2.95397428]),

[array([-0.375754,  0.346054,  2.808312]), array([0.023652, 0.369395, 2.667933]), array([-0.216575,  0.436592,  2.635937]), array([-0.144126,  0.230001,  2.807717]), array([-0.337644,  0.082849,  2.708891]), array([-0.013802,  0.082209,  2.589933]), array([-0.131495,  0.05428 ,  2.769967]), array([-0.405881,  0.070124,  2.714296]), array([0.062985, 0.169565, 2.457209]), array([-0.435602, -0.245418,  2.674939]), array([0.087483, 0.047185, 2.163232]), array([-0.400139, -0.317614,  2.656841]), array([0.106846, 0.070931, 2.086691]), array([-0.303899, -0.50232 ,  2.691523]), array([-0.052941, -0.493397,  2.691563]), array([-0.270691, -0.948775,  2.788165]), array([-0.183169, -0.931181,  2.72547 ]), array([-0.355204, -0.997303,  2.593021]), array([-0.215509, -0.938259,  2.509872]), array([-0.187929,  0.66573 ,  2.632176])]
[array([-0.377685,  0.347757,  2.822146]), array([0.014831, 0.375472, 2.664224]), array([-0.22767 ,  0.438186,  2.641685]), array([-0.144342,  0.235544,  2.813236]), array

[array([-0.43639612,  0.21983525,  2.50603771]), array([-0.07783946,  0.24015996,  2.48013414]), array([-0.26638466,  0.27678301,  2.40101053]), array([-0.24340116,  0.09912744,  2.5814488 ]), array([-0.44819019, -0.12021143,  2.48497696]), array([-0.02304362, -0.11929202,  2.45908307]), array([-0.22837483, -0.1057592 ,  2.59175932]), array([-0.50079789, -0.04494463,  2.51080536]), array([ 0.01671133, -0.0157217 ,  2.48256335]), array([-0.45687806, -0.31476456,  2.41860711]), array([ 0.00790992, -0.28264779,  2.37045395]), array([-0.48525088, -0.37582017,  2.40147108]), array([ 0.00305067, -0.34651371,  2.38580543]), array([-0.35350528, -0.62073781,  2.53455594]), array([-0.12271253, -0.62178913,  2.51447366]), array([-0.35927535, -1.00515129,  2.62925077]), array([-0.1265469 , -0.99677814,  2.64122972]), array([-0.37186893, -1.04485961,  2.46729349]), array([-0.13088259, -1.0503151 ,  2.48283152]), array([-0.26702693,  0.52086403,  2.37602151])]
[array([-0.43839142,  0.22059975,  2.51

[array([-0.41347901,  0.22596124,  2.52240881]), array([-0.05662561,  0.23351287,  2.47534898]), array([-0.24820501,  0.27415697,  2.40612096]), array([-0.22033184,  0.10105382,  2.59022366]), array([-0.43751157, -0.11696151,  2.48334539]), array([-0.01113546, -0.11629849,  2.46686165]), array([-0.21965668, -0.11179017,  2.59590316]), array([-0.47900767, -0.04197673,  2.5210677 ]), array([ 0.02437351, -0.03042692,  2.47849237]), array([-0.4694407 , -0.31925238,  2.42970255]), array([ 0.04459496, -0.29285662,  2.35348996]), array([-0.47541179, -0.38388859,  2.41080131]), array([ 0.05586645, -0.35950746,  2.34670422]), array([-0.34562884, -0.61869658,  2.51951926]), array([-0.11521256, -0.61968382,  2.50838772]), array([-0.35807547, -0.99723179,  2.63498309]), array([-0.12031038, -0.99713172,  2.62834392]), array([-0.36830709, -1.04566862,  2.47499052]), array([-0.12232438, -1.04791516,  2.46881456]), array([-0.23911773,  0.51305377,  2.36721778])]
[[-0.33977787  0.27664338  2.66783582 .

[[[[-3.57132511e-01  3.69861653e-01  2.68409998e+00]
   [-1.66066020e-03  3.54087896e-01  2.67285988e+00]
   [-1.80353434e-01  4.07576983e-01  2.58460110e+00]
   ...
   [-3.62178375e-01 -1.03673893e+00  2.62371762e+00]
   [-6.65554208e-02 -1.02873712e+00  2.57197900e+00]
   [-1.72621427e-01  6.59325906e-01  2.54934823e+00]]

  [[-3.74485020e-01  3.66327164e-01  2.67215094e+00]
   [-1.64860072e-02  3.55747195e-01  2.68164274e+00]
   [-1.91626569e-01  4.07117671e-01  2.58252069e+00]
   ...
   [-3.52011827e-01 -1.03924933e+00  2.63524305e+00]
   [-4.63873359e-02 -1.02147241e+00  2.56693144e+00]
   [-1.90723680e-01  6.56937102e-01  2.54794216e+00]]

  [[-3.73790718e-01  3.66532531e-01  2.67709913e+00]
   [-1.57904316e-02  3.53434328e-01  2.67416732e+00]
   [-1.93877359e-01  4.05688162e-01  2.58123549e+00]
   ...
   [-3.58055515e-01 -1.04135029e+00  2.64341503e+00]
   [-5.17319063e-02 -1.02651572e+00  2.57162248e+00]
   [-1.84604199e-01  6.56691629e-01  2.54576767e+00]]

  ...

  [[-3.51070

DONE=========
60800
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


KeyboardInterrupt: 